# Generated by Django 4.2.25 on 2025-10-31 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstb',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
