# Generated by Django 4.2.25 on 2025-11-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_alter_orderstb_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstb',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
